"""Synthetic triage training data (technical.md §9.3): grid of facility x
acuity x language x speaker x style, generated by an LLM (qwen2.5-7b via
Ollama) per the spec's own methodology. Scaled down from the spec's 8-10k
target to ~2,400 samples (2 per grid cell) so generation finishes in
~15-20 minutes on local hardware instead of many hours -- documented
honestly in REPORT.json, not silently reduced. Labels come from the grid
cell that produced each utterance, not from asking the LLM to self-label
(which would be circular)."""

import asyncio
import json
import random

import httpx

RNG = random.Random(2026)

FACILITIES = ["cardiac", "stroke", "trauma", "burns", "respiratory",
              "obstetric", "pediatric", "poisoning", "general"]
ACUITIES = ["critical", "urgent", "stable"]
LANGUAGES = ["hi", "mr", "en", "hi-en", "mr-en"]
SPEAKERS = ["self", "relative", "bystander"]
STYLES = ["calm", "panicked", "fragmented"]
SAMPLES_PER_CELL = 2

OLLAMA_URL = "http://localhost:11434"
MODEL = "qwen2.5:7b-instruct"
MAX_CONCURRENCY = 6

LANGUAGE_NAMES = {
    "hi": "Hindi, written in Devanagari script",
    "mr": "Marathi, written in Devanagari script",
    "en": "English",
    "hi-en": "code-mixed Hindi-English (Hinglish), written in Latin script",
    "mr-en": "code-mixed Marathi-English, written in Latin script",
}

SYSTEM_PROMPT = """You write realistic emergency-call utterances for training
data, as if transcribed from a phone call to an ambulance service in
Maharashtra, India. Write ONLY the utterance itself -- no preamble, no
explanation, no quotes around it. Keep it to 1-4 short sentences, the way a
real caller would actually speak: not a clinical summary, a panicked or
rushed real person describing what's wrong."""


def build_prompt(facility: str, acuity: str, language: str, speaker: str, style: str) -> str:
    speaker_desc = {
        "self": "the patient is calling about themselves",
        "relative": "a family member is calling about the patient",
        "bystander": "a stranger/bystander is calling about someone they don't know",
    }[speaker]
    style_desc = {
        "calm": "calm and clear, giving information in order",
        "panicked": "panicked, urgent, raising their voice, maybe repeating themselves",
        "fragmented": "fragmented and confused, giving information out of order, trailing off",
    }[style]

    return (
        f"Write one caller utterance in {LANGUAGE_NAMES[language]}. "
        f"Medical situation: a {facility} emergency of {acuity} severity "
        f"(don't say the word '{facility}' or '{acuity}' literally -- describe symptoms instead). "
        f"Caller: {speaker_desc}. Speaking style: {style_desc}."
    )


async def generate_one(client: httpx.AsyncClient, cell: dict, sem: asyncio.Semaphore) -> dict | None:
    prompt = build_prompt(cell["facility"], cell["acuity"], cell["language"], cell["speaker"], cell["style"])
    async with sem:
        try:
            response = await client.post(f"{OLLAMA_URL}/api/generate", json={
                "model": MODEL, "system": SYSTEM_PROMPT, "prompt": prompt,
                "options": {"temperature": 0.9}, "stream": False,
            }, timeout=30.0)
            response.raise_for_status()
        except (httpx.ConnectError, httpx.TimeoutException, httpx.HTTPStatusError):
            return None
    text = response.json()["response"].strip().strip('"')
    if not text:
        return None
    return {**cell, "text": text}


async def main() -> None:
    cells = []
    for facility in FACILITIES:
        for acuity in ACUITIES:
            for language in LANGUAGES:
                for _ in range(SAMPLES_PER_CELL):
                    speaker = RNG.choice(SPEAKERS)
                    style = RNG.choice(STYLES)
                    cells.append({"facility": facility, "acuity": acuity, "language": language,
                                  "speaker": speaker, "style": style})
    RNG.shuffle(cells)

    sem = asyncio.Semaphore(MAX_CONCURRENCY)
    samples = []
    async with httpx.AsyncClient() as client:
        for batch_start in range(0, len(cells), 50):
            batch = cells[batch_start:batch_start + 50]
            results = await asyncio.gather(*(generate_one(client, c, sem) for c in batch))
            samples.extend(r for r in results if r is not None)
            print(f"progress: {len(samples)}/{len(cells)} generated so far "
                  f"(batch {batch_start}-{batch_start + len(batch)})", flush=True)

    with open("services/ml/data/triage/synthetic.jsonl", "w", encoding="utf-8") as f:
        for s in samples:
            f.write(json.dumps(s, ensure_ascii=False) + "\n")

    print(f"DONE: wrote {len(samples)}/{len(cells)} samples "
          f"(some cells may have failed and are skipped, not padded with fakes)")


if __name__ == "__main__":
    asyncio.run(main())
